---
default_language_version:
  python: "python3"
fail_fast: true
ci:
    skip: ["poetry-lock", "prospector", "mypy"]

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.2.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-ast"
      - id: "check-byte-order-marker"
      - id: "check-docstring-first"
      - id: "check-executables-have-shebangs"
      - id: "check-json"
      - id: "check-symlinks"
      - id: "check-merge-conflict"
      - id: "check-vcs-permalinks"
      - id: "check-xml"
      - id: "check-yaml"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
      - id: "name-tests-test"
      - id: "trailing-whitespace"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-use-type-annotations

  - repo: "https://github.com/asottile/reorder_python_imports"
    rev: "v3.1.0"
    hooks:
      - id: "reorder-python-imports"
        args:
          - "--py39-plus"

  - repo: "https://github.com/psf/black"
    rev: "22.3.0"
    hooks:
      - id: "black"

  - repo: "local"
    hooks:

      - id: "prospector"
        name: "prospector"
        entry: "make lint"
        language: "system"
        types: ["python"]

      - id: "mypy"
        name: "mypy"
        entry: "make mypy"
        language: "system"
        types: ["python"]

  - repo: "https://github.com/pmav99/poetry11"
    rev: "de1e372981c75860c4d8b86c6368e9a9d8a88450"
    hooks:
      - id: "poetry-version"
      - id: "poetry-check"
      - id: "poetry-lock"
      - id: "poetry-export"
      - id: "poetry-export-dev"
