---
ci:
  skip: ["mypy", "docs"]
  autofix_prs: false
default_language_version:
  python: "python3"
fail_fast: false

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.6.0"
    hooks:
      - id: "check-added-large-files"
        exclude: "tests/cassettes/.*"
      - id: "check-ast"
      - id: "check-byte-order-marker"
      - id: "check-docstring-first"
      - id: "check-executables-have-shebangs"
      - id: "check-json"
      - id: "check-symlinks"
      - id: "check-merge-conflict"
      - id: "check-vcs-permalinks"
      - id: "check-xml"
      - id: "check-yaml"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
        exclude: ".+\\.ipynb"
      - id: "name-tests-test"
      - id: "trailing-whitespace"

  - repo: "https://github.com/pre-commit/pygrep-hooks"
    rev: "v1.10.0"
    hooks:
      - id: "python-check-blanket-noqa"
      - id: "python-check-blanket-type-ignore"
      - id: "python-use-type-annotations"

  - repo: "https://github.com/shellcheck-py/shellcheck-py"
    rev: "v0.10.0.1"
    hooks:
      - id: "shellcheck"

  - repo: "https://github.com/python-jsonschema/check-jsonschema"
    rev: "0.28.5"
    hooks:
      - id: "check-github-workflows"
      - id: "check-readthedocs"

  - repo: "https://github.com/asottile/reorder_python_imports"
    rev: "v3.13.0"
    hooks:
      - id: "reorder-python-imports"
        args:
          - "--py38-plus"

  - repo: "https://github.com/psf/black"
    rev: "24.4.2"
    hooks:
      - id: "black"

  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    # Ruff version.
    rev: 'v0.4.9'
    hooks:
      - id: "ruff"

  - repo: "https://github.com/kynan/nbstripout"
    rev: "0.7.1"
    hooks:
      - id: "nbstripout"

  - repo: "https://github.com/python-poetry/poetry"
    rev: "1.8.0"
    hooks:
      - id: "poetry-check"
      - id: "poetry-lock"
        args: ["--check"]
      - id: "poetry-export"
        name: 'poetry export main'
        args: ["--without-hashes", "--only", "main", "-f", "requirements.txt", "-o", "requirements/requirements.txt"]
      - id: "poetry-export"
        name: 'poetry export dev'
        args: ["--without-hashes", "--with", "dev", "--with", "docs", "--with", "jupyter", "-f", "requirements.txt", "-o", "requirements/requirements-dev.txt"]

  - repo: "local"
    hooks:

      - id: "mypy"
        name: "mypy"
        entry: "make mypy"
        language: "system"
        types: ["python"]

      - id: "docs"
        name: "docs"
        entry: "make docs"
        language: "system"
